before_install:
- rm ~/.m2/settings.xml
#  - sudo apt-get install ant-optional

# https://docs.travis-ci.com/user/languages/java/     
language: java
jdk:
   - oraclejdk9
   
#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2
  
#https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables
env:
- TOPJAVA_ROOT=$TRAVIS_BUILD_DIR


script:
  - mvn -f clean verify pom.xml 
#  - ant main
#-Pjacoco coveralls:report

#after_success: 

#notifications:
#  email:
#    recipients:
#      - davide.basile@isti.cnr.it