#before_install:
#  - sudo apt-get install ant-optional
     
language: java

jdk:
   - oraclejdk9

script:
   - mvn -f clean verify pom.xml 
#  - ant main
#-Pjacoco coveralls:report

#after_success: 

#notifications:
#  email:
#    recipients:
#      - davide.basile@isti.cnr.it