#https://github.com/travis-ci/travis-ci/issues/5805
before_install:
- rm ~/.m2/settings.xml

#  in case of ant this was needed
#  - sudo apt-get install ant-optional

# https://docs.travis-ci.com/user/languages/java/     
language: java
jdk:
   - oraclejdk9
 
   
#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2
  
#https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables
env:
- TOPJAVA_ROOT=$TRAVIS_BUILD_DIR


script:
- mvn jacoco:prepare-agent clean test jacoco:report coveralls:report

#  - ant main

#after_success: 
#- mvn coveralls:report

#notifications:
#  email:
#    recipients:
#      - davide.basile@isti.cnr.it